/**
 * @fileoverview Цей файл містить дані про статті блогу та надає функцію для їх отримання.
 *
 * @warning **THIS FILE IS AUTO-GENERATED.** Do not edit this file directly.
 * All changes will be overwritten. To modify the articles, edit the .mdx files
 * in `src/articles/` and re-run the pre-rendering script.
 * @see scripts/pre-render.mjs - The script that generates this file.
 * @version 1.1.0
 */

/**
 * @description Визначає структуру та контракт даних для однієї статті блогу.
 * Кожен об'єкт містить як метадані (frontmatter), так і повний контент статті.
 */
export interface Article {
  /**
   * @description URL-дружній ідентифікатор статті, унікальний в межах сайту.
   * @example "welcome-to-svitlogics"
   */
  readonly slug: string;
  /**
   * @description Заголовок статті, що відображається.
   */
  readonly title: string;
  /**
   * @description Короткий опис статті, що використовується для SEO та прев'ю.
   */
  readonly description: string;
  /**
   * @description Дата створення статті у форматі ISO 8601.
   * @example "2025-08-14"
   */
  readonly createdAt: string;
  /**
   * @description Дата останнього оновлення статті у форматі ISO 8601 (опціонально).
   */
  readonly updatedAt?: string;
  /**
   * @description Ім'я автора статті.
   */
  readonly author: string;
  /**
   * @description Повний URL до головного зображення статті.
   */
  readonly image: string;
  /**
   * @description Масив тегів для категоризації.
   */
  readonly tags: readonly string[];
  /**
   * @description Мова статті.
   */
  readonly language: "en" | "uk";
  /**
   * @description Канонічне посилання для SEO (опціонально).
   */
  readonly canonicalUrl?: string;
  /**
   * @description Значення для мета-тегу 'robots' (опціонально).
   */
  readonly robots?: string;
  /**
   * @description JSON-LD схема для розширених сніпетів у пошуку (опціонально).
   */
  readonly schema?: string;
  /**
   * @description Повний контент статті у форматі Markdown/MDX.
   */
  readonly content: string;
}

/**
 * @private
 * @description Внутрішній, незмінний масив, що містить усі статті.
 * Використання `as const` забезпечує глибоку незмінність (deep immutability) даних
 * на рівні типів, запобігаючи випадковим мутаціям під час виконання програми.
 * @type {readonly Article[]}
 */
const _articles = [
  {
    slug: "welcome-to-svitlogics",
    title: "Welcome to Svitlogics: A Tool for a New Era of Information",
    description:
      "An introduction to the mission, methodology, and core principles behind the Svitlogics project, written by its founder.",
    createdAt: "2025-08-14",
    updatedAt: "2025-08-16",
    author: "Eugene Kozlovsky",
    image: "https://svitlogics.com/images/articles/welcome-to-svitlogics.png",
    tags: ["Project Update", "Introduction"],
    language: "en",
    content:
      '![Welcome to Svitlogics: A Tool for a New Era of Information](/images/articles/welcome-to-svitlogics.png)\n\nMy name is Eugene Kozlovsky. Svitlogics is not just an application; it is my answer to a problem I live with every day.\n\nFor a long time, I felt a passive anger towards the manipulation I saw everywhere — in the news, on social media, in professional discourse. This feeling crystallized into action after I saw a viral post that used the tragedy of war to justify poor service. People saw patriotism; I saw a masterclass in emotional exploitation.\n\nIt was no longer enough to simply see the manipulation. I had to build a tool to help others see it too.\n\n### The Mission: Clarity in Chaos\n\nThe mission of Svitlogics is direct: to provide an accessible, transparent instrument for identifying manipulative techniques. It was developed as a solo project from my home in Kyiv, Ukraine, born from the daily reality of information warfare.\n\nThis tool is not a "truth machine." It does not deliver a simple "true" or "false" verdict. Effective manipulation rarely relies on a single, verifiable lie. Instead, it uses a complex web of emotional appeals, logical fallacies, and carefully framed narratives.\n\n### How It Works\n\nSvitlogics is designed as an auxiliary instrument for your own critical thinking. By leveraging a cascade of advanced AI models, it deconstructs text and provides a structured report across five core criteria:\n\n- Manipulative Content\n- Propagandistic Content\n- Disinformation\n- Unbiased Presentation\n- Emotional Tone\n\nMy core principle is that understanding _how_ a message is constructed to influence you is the first and most critical step toward resisting it.\n\nThis blog will serve as a platform to explore these topics further, share insights on new techniques of manipulation, and document the continued development of Svitlogics.\n\nThank you for joining me on this journey.',
  },
] as const;

/**
 * @description Повертає масив усіх доступних статей блогу.
 * Функція повертає посилання на незмінний масив. Будь-які спроби змінити
 * повернутий масив або його елементи призведуть до помилки компіляції TypeScript.
 *
 * @returns {readonly Article[]} Незмінний масив об'єктів статей.
 *
 * @example
 * import { getArticles } from './articles';
 *
 * const allArticles = getArticles();
 * console.log(`Total articles: ${allArticles.length}`);
 *
 * // Наступний код викличе помилку TypeScript, що є бажаною поведінкою:
 * // allArticles.push({ ... }); // Error: Property 'push' does not exist on type 'readonly Article[]'
 * // allArticles[0].slug = 'new-slug'; // Error: Cannot assign to 'slug' because it is a read-only property.
 */
export function getArticles(): readonly Article[] {
  return _articles;
}
