# === Netlify Configuration File v3.0 (Final Merged) ===

[build]
  command = "npm run build"
  publish = "dist"

# Контексти залишаємо для майбутнього
[context.production]
  [context.production.environment]

[context.branch-deploy]
  [context.branch-deploy.environment]

# Налаштування заголовків
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://challenges.cloudflare.com https://*.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' https://generativelanguage.googleapis.com https://www.google-analytics.com https://*.google-analytics.com; frame-src https://challenges.cloudflare.com; object-src 'none';"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"

# Налаштування редиректів
[[redirects]]
  from = "https://svitlogics.netlify.app/*"
  to = "https://svitlogics.com/:splat"
  status = 301
  force = true