import React from "react";
import { Helmet } from "react-helmet-async";

// --- НОВИЙ, ДЕТАЛЬНИЙ КОНТЕНТ ДИСКЛЕЙМЕРУ ---
const content = {
  seoTitle: "Disclaimer | Svitlogics",
  seoDescription:
    "Review the official Disclaimer for Svitlogics. This document outlines the limitations of our AI-powered analysis, user responsibilities, and our 'as is' service policy.",
  pageTitle: "DISCLAIMER",
  lastUpdated: "August 22, 2025",
  sections: [
    {
      id: "introduction",
      title: "1. Introduction",
      paragraphs: [
        'This Disclaimer governs your use of the Svitlogics web application ("the Service"). By using the Service, you accept this disclaimer in full. If you disagree with any part of this disclaimer, you must not use our Service. The information provided by Svitlogics is for general informational purposes only.',
        "The core purpose of this document is to ensure you, the user, have a clear and unambiguous understanding of the capabilities and, more importantly, the **limitations** of the AI-driven analysis provided by Svitlogics.",
      ],
    },
    {
      id: "no-professional-advice",
      title: "2. No Professional Advice",
      paragraphs: [
        "The analysis and content generated by Svitlogics are **not intended to be a substitute for professional advice**. The Service provides automated textual analysis based on pre-defined criteria and should not be considered legal, financial, journalistic, or any other form of professional counsel.",
        "You should not rely on the information provided by the Service as an alternative to advice from a qualified professional. You should never delay seeking professional advice, disregard professional advice, or commence or discontinue any action because of information provided by our Service. The final interpretation and any decisions made based on the analysis rest solely with you.",
      ],
    },
    {
      id: "accuracy-of-information",
      title: "3. Accuracy of Information and AI Limitations",
      paragraphs: [
        "Svitlogics is an **auxiliary instrument for critical thinking, not a “truth machine” or a fact-checking service.** We make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the analysis provided.",
        "You must acknowledge the inherent limitations of artificial intelligence:",
      ],
      list: [
        "<strong>Infallibility:</strong> No AI analysis is 100% infallible. AI models can misinterpret context, fail to understand nuanced language, overlook sarcasm, or generate outputs that may contain errors or inaccuracies.",
        "<strong>No “Truth” Verdict:</strong> The Service does not, and cannot, deliver a definitive “true” or “false” verdict on the text you submit. Effective manipulation often relies on carefully framed narratives and emotional appeals rather than single, verifiable lies.",
        "<strong>Subjectivity:</strong> While calibrated with objective criteria, the analysis of elements like 'Emotional Tone' or 'Unbiased Presentation' can involve a degree of interpretation by the AI that may not align with human perception.",
        "<strong>Contextual Blindness:</strong> The AI analyzes only the text you provide. It has no knowledge of the author's intent, the broader context in which the text was published, or any events that occurred before or after its creation.",
      ],
      finalParagraph:
        "Any reliance you place on the analysis generated by Svitlogics is **strictly at your own risk.**",
    },
    {
      id: "no-warranties",
      title: "4. No Warranties",
      paragraphs: [
        'The Service is provided on an "as is" and "as available" basis without any representations or warranties, express or implied. To the fullest extent permissible by law, we disclaim all warranties.',
        "Without prejudice to the generality of the foregoing paragraph, we do not warrant that:",
      ],
      list: [
        "The Service will be constantly available, or available at all;",
        "The information and analysis provided by the Service is complete, true, accurate, or non-misleading;",
        "The Service will meet your specific requirements or produce a specific outcome.",
      ],
    },
    {
      id: "limitation-of-liability",
      title: "5. Limitation of Liability",
      paragraphs: [
        "Our liability to you is limited. In no event will Eugene Kozlovsky or Svitlogics be liable for any direct, indirect, special, incidental, consequential, or punitive damages arising out of your use of, or inability to use, the Service. This includes, but is not limited to, damages for loss of profits, data, or other intangibles, even if we have been advised of the possibility of such damages.",
        'This limitation of liability is a fundamental element of the basis of the bargain between you and us. The Service would not be provided without such limitations. For full details, please refer to the "Limitation of Liability" section in our <a href="/terms-of-use" class="text-blue-accent hover:underline">Terms of Use</a>.',
      ],
    },
    {
      id: "external-links",
      title: "6. External Links Disclaimer",
      paragraphs: [
        "The Svitlogics website may contain links to other websites or content belonging to or originating from third parties. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us.",
        "WE DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR THE ACCURACY OR RELIABILITY OF ANY INFORMATION OFFERED BY THIRD-PARTY WEBSITES LINKED THROUGH THE SITE. We will not be a party to or in any way be responsible for monitoring any transaction between you and third-party providers of products or services.",
      ],
    },
    {
      id: "beta-service",
      title: "7. Public Beta Status",
      paragraphs: [
        "You acknowledge that Svitlogics is currently in a public beta phase. The features and functionality of the Service are subject to change without notice and may contain bugs, errors, or other performance limitations. All analysis results generated during the beta phase should be considered preliminary.",
      ],
    },
    {
      id: "contact",
      title: "8. Contact Us",
      paragraphs: [
        'If you have any questions about this Disclaimer, please contact us via our <a href="/contact" class="text-blue-accent hover:underline">Contact page</a>.',
      ],
    },
  ],
};

const PolicySection: React.FC<{ section: any }> = ({ section }) => (
  <section
    aria-labelledby={`section-title-${section.title.replace(/\s+/g, "-")}`}
  >
    <h2
      id={`section-title-${section.title.replace(/\s+/g, "-")}`}
      className="font-mono font-semibold text-h2-mobile lg:text-h2-desktop text-black mb-6 normal-case"
    >
      {section.title}
    </h2>
    <div className="space-y-4 font-mono font-normal text-body-main leading-body text-black">
      {section.paragraphs &&
        section.paragraphs.map((p: string, i: number) => (
          <p key={i} dangerouslySetInnerHTML={{ __html: p }} />
        ))}
      {section.list && (
        <ul className="space-y-2 list-disc ml-6 mt-4">
          {section.list.map((item: string) => (
            <li
              key={item.substring(0, 20)}
              dangerouslySetInnerHTML={{ __html: item }}
            />
          ))}
        </ul>
      )}
      {section.finalParagraph && (
        <p
          className="mt-4"
          dangerouslySetInnerHTML={{ __html: section.finalParagraph }}
        />
      )}
    </div>
  </section>
);

const DisclaimerPage: React.FC = () => {
  return (
    <>
      <Helmet>
        <title>{content.seoTitle}</title>
        <meta name="description" content={content.seoDescription} />
        <link rel="canonical" href="https://svitlogics.com/disclaimer" />
        <meta property="og:title" content={content.seoTitle} />
        <meta property="og:description" content={content.seoDescription} />
        <meta property="og:url" content="https://svitlogics.com/disclaimer" />
        <meta property="og:type" content="article" />
      </Helmet>

      <div className="container-main pt-16 pb-16">
        <h1 className="font-mono font-bold text-h1-mobile normal-case md:uppercase lg:text-h1-desktop text-black mb-4 text-left">
          {content.pageTitle}
        </h1>
        <p className="font-mono text-ui-label text-text-secondary mb-16">
          Last Updated: {content.lastUpdated}
        </p>

        <div className="max-w-3xl space-y-12">
          {content.sections.map((section) => (
            <PolicySection key={section.title} section={section} />
          ))}
        </div>
      </div>
    </>
  );
};

export default DisclaimerPage;
