import React, { useMemo } from "react";
import { Helmet } from "react-helmet-async";
import DOMPurify from "dompurify";

// --- Типізація та Константи ---

/** @description Визначає структуру основної секції політики. */
interface PolicySectionData {
  readonly id: string;
  readonly title: string;
  readonly paragraphs: readonly string[];
  readonly list?: readonly string[];
  readonly finalParagraph?: string;
}

/**
 * @description Статичний контент сторінки. `as const` забезпечує глибоку незмінність.
 */
const content = {
  seoTitle: "DISCLAIMER | SVITLOGICS",
  seoDescription:
    'This document outlines the Svitlogics Disclaimer, detailing service limitations, user responsibilities, and the "as is" policy for AI-powered analysis.',
  canonicalUrl: "https://svitlogics.com/disclaimer",
  pageTitle: "DISCLAIMER",
  lastUpdated: "August 22, 2025",
  sections: [
    {
      id: "introduction",
      title: "1. Introduction",
      paragraphs: [
        'This Disclaimer governs your use of the Svitlogics web application ("the Service"). By using the Service, you accept this disclaimer in full. If you disagree with any part of this disclaimer, you must not use the Service. The information provided by Svitlogics is for general informational purposes only.',
        "The core purpose of this document is to provide the user with a clear and unambiguous understanding of the capabilities and, more importantly, the <strong>limitations</strong> of the AI-driven analysis provided by Svitlogics.",
      ],
    },
    {
      id: "no-professional-advice",
      title: "2. No Professional Advice",
      paragraphs: [
        "The analysis and content generated by Svitlogics are <strong>not a substitute for professional advice</strong>. The Service provides automated textual analysis based on pre-defined criteria and should not be considered legal, financial, journalistic, or any other form of professional counsel.",
        "You should not rely on the information provided by the Service as an alternative to advice from a qualified professional. You should not delay seeking professional advice, disregard professional advice, or commence or discontinue any action because of information provided by the Service. The final interpretation and any decisions made based on the analysis rest solely with you.",
      ],
    },
    {
      id: "accuracy-of-information",
      title: "3. Accuracy of Information and AI Limitations",
      paragraphs: [
        "Svitlogics is an <strong>auxiliary instrument for critical thinking, not a “truth machine” or a fact-checking service.</strong> Svitlogics makes no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the analysis provided.",
        "The user must acknowledge the inherent limitations of artificial intelligence:",
      ],
      list: [
        "<strong>Infallibility:</strong> No AI analysis is 100% infallible. AI models can misinterpret context, fail to understand nuanced language, overlook sarcasm, or generate outputs that contain errors or inaccuracies.",
        "<strong>No “Truth” Verdict:</strong> The Service does not, and cannot, deliver a definitive “true” or “false” verdict on the submitted text. Effective manipulation often relies on carefully framed narratives and emotional appeals rather than single, verifiable lies.",
        "<strong>Subjectivity:</strong> While calibrated with objective criteria, the analysis of elements like 'Emotional Tone' or 'Unbiased Presentation' can involve a degree of interpretation by the AI that may not align with human perception.",
        "<strong>Contextual Blindness:</strong> The AI analyzes only the provided text. It has no knowledge of the author's intent, the broader context in which the text was published, or any events that occurred before or after its creation.",
      ],
      finalParagraph:
        "Any reliance placed on the analysis generated by Svitlogics is <strong>strictly at the user's own risk.</strong>",
    },
    {
      id: "no-warranties",
      title: "4. No Warranties",
      paragraphs: [
        'The Service is provided on an "as is" and "as available" basis without any representations or warranties, express or implied. To the fullest extent permissible by law, all warranties are disclaimed.',
        "Without prejudice to the generality of the foregoing paragraph, Svitlogics does not warrant that:",
      ],
      list: [
        "The Service will be constantly available, or available at all;",
        "The information and analysis provided by the Service is complete, true, accurate, or non-misleading;",
        "The Service will meet specific user requirements or produce a specific outcome.",
      ],
    },
    {
      id: "limitation-of-liability",
      title: "5. Limitation of Liability",
      paragraphs: [
        "The liability of the Service is limited. In no event will Svitlogics be liable for any direct, indirect, special, incidental, consequential, or punitive damages arising out of the use of, or inability to use, the Service. This includes, but is not limited to, damages for loss of profits, data, or other intangibles, even if advised of the possibility of such damages.",
        'This limitation of liability is a fundamental element of the basis of the bargain between the user and the Service. The Service would not be provided without such limitations. For a complete definition, refer to the "Limitation of Liability" section in the <a href="/terms-of-use">Terms of Use</a>.',
      ],
    },
    {
      id: "external-links",
      title: "6. External Links Disclaimer",
      paragraphs: [
        "The Svitlogics website may contain links to other websites or content belonging to or originating from third parties. Svitlogics does not investigate, monitor, or check such external links for accuracy, adequacy, validity, reliability, availability, or completeness.",
        "THE SERVICE DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR THE ACCURACY OR RELIABILITY OF ANY INFORMATION OFFERED BY THIRD-PARTY WEBSITES LINKED THROUGH THE SITE. The Service will not be a party to or in any way be responsible for monitoring any transaction between you and third-party providers of products or services.",
      ],
    },
    {
      id: "beta-service",
      title: "7. Public Beta Status",
      paragraphs: [
        "The user acknowledges that Svitlogics is currently in a public beta phase. The features and functionality of the Service are subject to change without notice and may contain bugs, errors, or other performance limitations. All analysis results generated during the beta phase are considered preliminary.",
      ],
    },
    {
      id: "contact",
      title: "8. Contact Us",
      paragraphs: [
        'For any questions about this Disclaimer, contact the Service via the <a href="/contact">Contact page</a>.',
      ],
    },
  ],
} as const;

// --- Мемоїзовані та Безпечні Підкомпоненти ---

/**
 * @description Безпечно рендерить HTML-рядок, попередньо очистивши його.
 * @param {string} rawHtml - Необроблений HTML-рядок.
 * @returns {{ __html: string }} Об'єкт, сумісний з `dangerouslySetInnerHTML`.
 */
const createSanitizedHtml = (rawHtml: string): { __html: string } => {
  const sanitizedHtml = DOMPurify.sanitize(rawHtml, {
    USE_PROFILES: { html: true },
    ALLOWED_TAGS: ["strong", "em", "a"],
    ALLOWED_ATTR: ["href", "target", "rel"],
  });
  return { __html: sanitizedHtml };
};

/** @description Пропси для підкомпонента `PolicySection`. */
interface PolicySectionProps {
  section: PolicySectionData;
}

const PolicySection: React.FC<PolicySectionProps> = React.memo(
  ({ section }) => {
    const headingId = useMemo(
      () => `section-title-${section.id}`,
      [section.id]
    );

    return (
      <section aria-labelledby={headingId}>
        <h2
          id={headingId}
          className="mb-6 font-semibold text-black text-h2-mobile lg:text-h2-desktop"
        >
          {section.title}
        </h2>
        <div className="space-y-4 text-body-main text-black">
          {section.paragraphs.map((p, i) => (
            <p key={i} dangerouslySetInnerHTML={createSanitizedHtml(p)} />
          ))}
          {section.list && (
            <ul className="ml-6 list-disc space-y-2 pt-2">
              {section.list.map((item, index) => (
                <li
                  key={index}
                  dangerouslySetInnerHTML={createSanitizedHtml(item)}
                />
              ))}
            </ul>
          )}
          {section.finalParagraph && (
            <p
              className="pt-2"
              dangerouslySetInnerHTML={createSanitizedHtml(
                section.finalParagraph
              )}
            />
          )}
        </div>
      </section>
    );
  }
);
PolicySection.displayName = "PolicySection";

/**
 * @description Статична сторінка "Disclaimer".
 * @component
 */
const DisclaimerPage: React.FC = () => {
  const renderedSections = useMemo(
    () =>
      content.sections.map((section) => (
        <PolicySection key={section.id} section={section} />
      )),
    []
  );

  return (
    <>
      <Helmet>
        <title>{content.seoTitle}</title>
        <meta name="description" content={content.seoDescription} />
        <link rel="canonical" href={content.canonicalUrl} />
        <meta property="og:title" content={content.seoTitle} />
        <meta property="og:description" content={content.seoDescription} />
        <meta property="og:url" content={content.canonicalUrl} />
        <meta property="og:type" content="article" />
      </Helmet>

      <div className="container-main">
        <header>
          <h1 className="mb-4 font-bold text-black text-h1-mobile md:uppercase lg:text-h1-desktop">
            {content.pageTitle}
          </h1>
          <p className="mb-16 uppercase text-text-secondary text-ui-label">
            Last Updated: {content.lastUpdated}
          </p>
        </header>

        <main className="max-w-3xl space-y-16">{renderedSections}</main>
      </div>
    </>
  );
};

export default React.memo(DisclaimerPage);
