import React from 'react';
import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
// import { useTranslation } from 'react-i18next';

// Фінальний контент
const content = {
  seoTitle: "Terms of Use | Svitlogics",
  seoDescription: "Review the terms and conditions for using the Svitlogics web application. This page outlines user responsibilities and the service's limitations.",
  pageTitle: "TERMS OF USE",
  lastUpdated: "Last Updated: June 29, 2025",
  sections: [
    {
      title: "1. Acceptance of terms",
      text: "By accessing or using the Svitlogics web application (\"the Service\"), you agree to be bound by these Terms of Use. If you do not agree to these terms, you are not permitted to use the Service."
    },
    {
      title: "2. Description of service",
      text: "Svitlogics is an AI-powered tool that provides automated analysis of textual content. The Service is intended as an <strong>auxiliary instrument to aid critical thinking</strong> and is not a substitute for professional advice or independent fact-checking."
    },
    {
      title: "3. Beta version and disclaimer of warranties",
      text: "The Service is provided on an \"as is\" and \"as available\" basis. You acknowledge that the Service is a Beta version and may contain errors or inaccuracies. The analysis is generated by AI models from Google and is not guaranteed to be 100% accurate or complete. Svitlogics makes no warranties of any kind, express or implied, regarding the operation of the Service or the accuracy of the information it provides."
    },
    {
      title: "4. User conduct",
      list: [
        "You agree to use the Service for lawful purposes only and in a manner that does not infringe on the rights of others.",
        "You are solely responsible for the text you submit. Do not submit content that is illegal, defamatory, or contains sensitive personal information.",
        "You agree not to misuse the Service through automated scripts, bots, or other means that could damage or overburden its infrastructure."
      ]
    },
    {
      title: "5. Intellectual property",
      text: "The Svitlogics application—including its design, branding, and analysis structure—is the intellectual property of its developer. The analytical output generated from text you provide is for your personal, non-commercial, and informational use."
    },
    {
      title: "6. Limitation of liability",
      text: "In no event shall Eugene Kozlovsky be liable for any damages arising from your use of or inability to use the Service. Use of the Service is entirely at your own risk."
    },
    {
      title: "7. Third-party services",
      textParts: [
        { type: 'text', content: "The Service relies on Google's AI Platform API. Your use of the Service is also subject to Google's applicable terms and policies. Refer to the Svitlogics" },
        { type: 'link', to: '/privacy-policy', content: "Privacy Policy" },
        { type: 'text', content: " for more details." }
      ]
    },
    {
      title: "8. Changes to terms",
      text: "Svitlogics reserves the right to modify these Terms of Use at any time. Changes will be posted on this page. The 'Last Updated' date will indicate the latest revision."
    },
    {
      title: "9. Contact",
      textParts: [
        { type: 'text', content: "For questions about these Terms of Use, use the" },
        { type: 'link', to: '/contact', content: "Contact page" },
        { type: 'text', content: "." }
      ]
    }
  ]
};

// Підкомпонент для однієї секції
const TermsSection: React.FC<{ section: typeof content.sections[0] }> = ({ section }) => (
  <section aria-labelledby={`section-title-${section.title.replace(/\s+/g, '-')}`}>
    <h2 id={`section-title-${section.title.replace(/\s+/g, '-')}`} className="font-mono font-semibold text-h2-mobile lg:text-h2-desktop text-black mb-6 normal-case">
      {section.title}
    </h2>
    <div className="space-y-4 font-mono font-normal text-body-main leading-body text-black">
      {section.text && <p dangerouslySetInnerHTML={{ __html: section.text }} />}
      
      {section.textParts && (
        <p>
          {section.textParts.map((part, index) => {
            if (part.type === 'link') {
              return (
                <Link key={index} to={part.to as string} className="text-blue-accent hover:underline focus-visible:underline">
                  {part.content}
                </Link>
              );
            }
            return <span key={index}>{part.content === '.' ? part.content : `${part.content} `}</span>;
          })}
        </p>
      )}

      {section.list && (
        <ul className="space-y-2 list-disc ml-6">
          {section.list.map((item) => (
            <li key={item.substring(0, 20)}>{item}</li>
          ))}
        </ul>
      )}
    </div>
  </section>
);

const TermsOfUsePage: React.FC = () => {
  // const { t } = useTranslation();

  return (
    <>
      <Helmet>
        <title>{content.seoTitle}</title>
        <meta name="description" content={content.seoDescription} />
        <link rel="canonical" href="https://svitlogics.com/terms-of-use" />
        <meta property="og:title" content={content.seoTitle} />
        <meta property="og:description" content={content.seoDescription} />
        <meta property="og:url" content="https://svitlogics.com/terms-of-use" />
        <meta property="og:type" content="article" />
      </Helmet>
      
      <div className="container-main pt-16 pb-16">
        <h1 className="font-mono font-bold text-h1-mobile normal-case md:uppercase lg:text-h1-desktop text-black mb-4 text-left">
          {content.pageTitle}
        </h1>
        <p className="font-mono text-ui-label text-text-secondary mb-16">
          {content.lastUpdated}
        </p>
        
        <div className="max-w-3xl space-y-12">
          {content.sections.map((section) => (
            <TermsSection key={section.title} section={section} />
          ))}
        </div>
      </div>
    </>
  );
};

export default TermsOfUsePage;